=== jbalazs97/U2ZEIG_XMLGyak/U2ZEIG_10_12/JB_konyv1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="könyvek">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="könyv">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cim" type="xs:string" />
              <xs:element name="szerzo" type="xs:string" />
              <xs:element name="szereplo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nev" type="xs:string" />
                    <xs:element name="baratja" type="xs:string" />
                    <xs:element name="szuletett" type="xs:string" />
                    <xs:element name="jellemzes" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="masikszereplo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nev" type="xs:string" />
                    <xs:element name="baratja" type="xs:string" />
                    <xs:element name="szuletett" type="xs:string" />
                    <xs:element name="jellemzes" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="isbn" type="xs:unsignedLong" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jbalazs97/U2ZEIG_XMLGyak/U2ZEIG_10_12/JB_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>
<könyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JB_konyv1.xsd">
    <könyv isbn="5995269840014">
        <cim>Harry Potter</cim>
        <szerzo>J. K. Rowling</szerzo>
        <szereplo>
            <nev>Harry Potter</nev>
            <baratja>Hermione Granger</baratja>
            <szuletett>1997.05.17.</szuletett>
            <jellemzes>Magabiztos</jellemzes>
        </szereplo>
        <masikszereplo>
            <nev>Hermione Granger</nev>
            <baratja>Harry Potter</baratja>
            <szuletett>1998.01.26.</szuletett>
            <jellemzes>Okostojás</jellemzes>
        </masikszereplo>
    </könyv>
</könyvek>
