=== jbalazs97/U2ZEIG_XMLGyak/U2ZEIG_10_05/JB_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="konyvek">
            <xs:complexType>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="konyv">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="cim" type="xs:string" />
                                <xs:element name="ev" type="xs:unsignedShort" />
                                <xs:element name="kiado" type="xs:string" />
                                <xs:element name="szerzo" type="xs:string" maxOccurs="unbounded" />
                                <xs:element name="absztrakt" type="xs:string" />
                            </xs:sequence>
                            <xs:attribute name="kod" type="xs:string" use="required" />
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:schema>

=== jbalazs97/U2ZEIG_XMLGyak/U2ZEIG_10_05/JB_konyv.xml
<?xml version="1.0" encoding="utf-8"?>
<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JB_konyv.xsd">
    <konyv kod="ID-01">
        <cim>Adatbázis Rendszerek</cim>
        <ev> 1999</ev>
        <kiado>Valami Kft.</kiado>
        <szerzo>Nagy Sándor</szerzo>
        <absztrakt>Rendszer</absztrakt>

    </konyv>
    <konyv kod="ID-02">
        <cim>Programozás alapjai</cim>
        <ev> 2005</ev>
        <kiado>Valami Kft.</kiado>
        <szerzo>Kiss Mária</szerzo>
        <absztrakt>Alap</absztrakt>

    </konyv>
    <konyv kod="ID-03">
        <cim>Hálózatok</cim>
        <ev> 2009</ev>
        <kiado>Lexika kiadó.</kiado>
        <szerzo>Péter Albert</szerzo>
        <absztrakt>Valami</absztrakt>

    </konyv>



</konyvek>
